version: '0.1.0'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eco-smart-api
      POSTGRES_PASSWORD: 82KQ6KkyLo5
      POSTGRES_DB: eco-smart
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
    networks:
      - host

  # api:
  #   build:
  #     context: . # assuming Dockerfile is in the root of your project
  #   container_name: eco-smart-api
  #   restart: unless-stopped
  #   depends_on:
  #     - postgresql
  #   environment:
  #     DATABASE_URL: postgres://eco-smart-api:82KQ6KkyLo5@postgresql:5432/eco-smart
  #   ports:
  #     - 8080:8080 # adjust this based on the port your API uses
  #   networks:
  #     - host

volumes:
  postgresql:


networks:
  host:
    driver: bridge
